In [1]:
import numpy as np
a=np.random.randn(3)
a

array([ 0.44881383,  1.31496783, -1.06704262])

In [2]:
np.random.seed(7)
a=np.random.randint(1,10,3)
a

array([5, 7, 4])

In [3]:
a=np.random.randint(1,50,36)
a

array([20, 24, 40, 29, 15, 24,  9, 26, 47, 43, 27,  9, 40, 39,  5, 49,  8,
       45,  1, 12,  7, 20, 45,  6, 25, 49,  1, 35, 10, 15, 39,  5, 47, 10,
       24, 36])

In [4]:
a=a.reshape(4,9) #no. of rows and no.of columns 
a

array([[20, 24, 40, 29, 15, 24,  9, 26, 47],
       [43, 27,  9, 40, 39,  5, 49,  8, 45],
       [ 1, 12,  7, 20, 45,  6, 25, 49,  1],
       [35, 10, 15, 39,  5, 47, 10, 24, 36]])

In [5]:
a=a.reshape(-1,18)
a

array([[20, 24, 40, 29, 15, 24,  9, 26, 47, 43, 27,  9, 40, 39,  5, 49,
         8, 45],
       [ 1, 12,  7, 20, 45,  6, 25, 49,  1, 35, 10, 15, 39,  5, 47, 10,
        24, 36]])

In [6]:
a.shape

(2, 18)

In [7]:
#view vs copy method

In [8]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6]  #slicing
b

array([40, 50, 60])

In [9]:
b[:]=0

In [10]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6].copy() #slicing
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [11]:
#conditional selection

In [12]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [14]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [15]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [16]:
c=a<=10
a[c]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
c=a%2==0
a[c]

array([ 2,  4,  6,  8, 10, 12, 14])

In [18]:
#operations on array

In [19]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [20]:
a+2

array([3, 4, 5, 6])

In [21]:
a**2

array([ 1,  4,  9, 16])

In [22]:
a

array([1, 2, 3, 4])

In [23]:
a= a.reshape(2,2)

In [24]:
b=np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [25]:
a

array([[1, 2],
       [3, 4]])

In [26]:
b

array([[5, 6],
       [7, 8]])

In [27]:
a+b

array([[ 6,  8],
       [10, 12]])

In [28]:
b-a

array([[4, 4],
       [4, 4]])

In [29]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [30]:
a*b

array([[ 5, 12],
       [21, 32]])

In [31]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [32]:
a.dot(b)      #for matrix multiplication 

array([[19, 22],
       [43, 50]])

In [33]:
a=np.array([10,20,30,40,50])

In [34]:
np.min(a)

10

In [35]:
np.max(a)

50

In [36]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [37]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [38]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [39]:
np.argmin(a)   #with index value

0

In [40]:
np.argmax(a)

4

In [41]:
#linspace() = this functions returns value between a given range and with a same gap between consicuitive elments

In [42]:
a=np.linspace(1,2,5) #have the same differnce i.e..25
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [43]:
a=np.linspace(2,20,10)
a


array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [44]:
np.random.seed(122)

In [45]:
a=np.random.randint(1,21,9).reshape(3,3)

In [46]:
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [47]:
np.sum(a)

116

In [48]:
np.sum(a,axis=1)

array([40, 46, 30])

In [49]:
np.sum(a,axis=0)

array([36, 40, 40])

In [50]:
a.min

<function ndarray.min>

In [51]:
np.min(a)

3

In [52]:
np.max(a)

17

In [53]:
np.cumsum(a)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116])

In [54]:
np.cumproduct(a)

array([        16,        176,       2288,      38896,     505648,
          8090368,   24271104,  388337664, 4271714304])

In [55]:
#np.unique(arr ,return_index =True ,  return_count=True)
#the array with unique value
#the array with respective index value
#the array with counting of frequency

In [56]:
a=np.array([10,20,30,40,30,40,50,60,70,70,80])
np.unique(a,return_index=True ,return_counts=True)

(array([10, 20, 30, 40, 50, 60, 70, 80]),
 array([ 0,  1,  2,  3,  6,  7,  8, 10]),
 array([1, 1, 2, 2, 1, 1, 2, 1]))

In [57]:
#horizontal and vertical stacking

In [58]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [59]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [62]:
a=np.random.randint(1,10,10)
a

array([6, 7, 4, 5, 4, 4, 1, 5, 2, 7])

In [63]:
a=np.array([10,11,12,13,14,15,16,17,18,19,20])
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [64]:
a=[11,12,13,14,15,16,17,18,19,20]
b=np.array(a)
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [65]:
a=array=np.ones(5)*5
a

array([5., 5., 5., 5., 5.])

In [66]:
a=np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
a = a.reshape(3, 3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [70]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [71]:
a = a.reshape(3, 3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [72]:
a=np.random.randint(0,1,9)
a
a.reshape(3,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [73]:
a=np.array([1,2,3,4]
           )
b=np.array([10,20,30,40])
a

array([1, 2, 3, 4])

In [74]:
b

array([10, 20, 30, 40])

In [75]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [76]:
np.hstack((a,b))

array([ 1,  2,  3,  4, 10, 20, 30, 40])